import type { Account, FinancialState, Priority, Recurring } from '@/lib/types'
import {
  ISODate,
  addDays,
  daysBetween,
  fromISO,
  monthlyOccurrences,
  nextDayOfMonth,
  today,
  yearlyOccurrences,
} from '@/lib/dates'

export type EventKind = 'income' | 'bill' | 'subscription' | 'card_payment' | 'everyday' | 'transfer'

/**
 * One dated money movement in the projection. `amount` is always positive;
 * direction is carried by the account fields, so a transfer can debit one
 * account and credit another without becoming two half-truths.
 */
export interface LedgerEvent {
  id: string
  date: ISODate
  label: string
  kind: EventKind
  amount: number
  /** Credited account. `null` for pure outflows. */
  toAccountId: string | null
  /** Debited account. `null` for pure inflows. */
  fromAccountId: string | null
  confidence: number
  priority?: Priority
  sourceId: string
  automated?: boolean
  rationale?: string
}

/** Pull an amount toward the pessimistic end of its range. */
function skew(r: Recurring, conservatism: number) {
  const worst = r.kind === 'income' ? Math.min(r.minAmount, r.amount) : Math.max(r.maxAmount, r.amount)
  return r.amount + (worst - r.amount) * conservatism
}

/** Income arrives somewhere inside its window; the midpoint is the fair guess. */
function incomeDay(r: Recurring) {
  const end = r.dayEnd ?? r.day
  return end >= r.day ? Math.round((r.day + end) / 2) : r.day
}

function occurrences(r: Recurring, from: ISODate, to: ISODate): ISODate[] {
  const day = r.kind === 'income' ? incomeDay(r) : r.day
  if (r.cadence === 'monthly') return monthlyOccurrences(day, from, to)
  if (r.cadence === 'annual') {
    const month = r.month ?? (r.startedOn ? fromISO(r.startedOn).getMonth() + 1 : 1)
    return yearlyOccurrences(month, day, from, to)
  }
  // Quarterly, anchored to the month it started so the cadence stays true.
  const anchor = r.startedOn ? fromISO(r.startedOn).getMonth() + 1 : 1
  return monthlyOccurrences(day, from, to).filter((d) => (Number(d.slice(5, 7)) - anchor + 12) % 3 === 0)
}

export function paymentAccountFor(state: FinancialState, card: Account): Account | undefined {
  if (card.paymentAccountId) {
    const explicit = state.accounts.find((a) => a.id === card.paymentAccountId)
    if (explicit) return explicit
  }
  return (
    state.accounts.find((a) => a.kind === 'bills' && !a.archived) ??
    state.accounts.find((a) => a.kind === 'spending' && !a.archived)
  )
}

/**
 * Average daily everyday spending, learned from the ledger.
 *
 * The previous version made the user type a monthly figure. Now that
 * transactions exist, the app measures it: anything that is not a transfer and
 * not generated by a recurring schedule is everyday spending, averaged over
 * however many days of history exist (capped at 90).
 */
export function everydayDailyBurn(state: FinancialState): number {
  const to = today()
  const from = addDays(to, -90)
  const spends = state.transactions.filter(
    (t) => !t.transfer && !t.recurringId && t.amount < 0 && t.date >= from && t.date <= to,
  )
  if (!spends.length) return 0

  const oldest = spends.reduce((min, t) => (t.date < min ? t.date : min), to)
  const span = Math.max(7, Math.min(90, daysBetween(oldest, to) + 1))
  const total = spends.reduce((s, t) => s + Math.abs(t.amount), 0)
  return total / span
}

/** Which account everyday spending actually comes out of, by observed volume. */
function everydayAccount(state: FinancialState): Account | undefined {
  const cash = state.accounts.filter((a) => !a.archived && a.kind !== 'credit')
  if (!cash.length) return undefined

  const from = addDays(today(), -90)
  const weight = new Map<string, number>()
  for (const t of state.transactions) {
    if (t.transfer || t.recurringId || t.amount >= 0 || t.date < from) continue
    weight.set(t.accountId, (weight.get(t.accountId) ?? 0) + Math.abs(t.amount))
  }

  const ranked = cash
    .map((a) => ({ a, w: weight.get(a.id) ?? 0 }))
    .sort((x, y) => y.w - x.w)

  if (ranked[0]?.w > 0) return ranked[0].a
  return cash.find((a) => a.kind === 'spending') ?? cash[0]
}

/**
 * Expand every recurring schedule into concrete dated events across
 * `[from, to]`. Pure — the rule engine layers its transfers on top.
 */
export function generateScheduledEvents(
  state: FinancialState,
  from: ISODate,
  to: ISODate,
): LedgerEvent[] {
  const events: LedgerEvent[] = []
  const c = state.settings.forecastConservatism

  for (const r of state.recurring) {
    if (!r.active) continue
    const amount = skew(r, c)
    for (const date of occurrences(r, from, to)) {
      events.push({
        id: `rec:${r.id}:${date}`,
        date,
        label: r.name,
        kind: r.kind,
        amount,
        toAccountId: r.kind === 'income' ? r.accountId : null,
        fromAccountId: r.kind === 'income' ? null : r.accountId,
        confidence: r.kind === 'income' ? r.confidence : 1,
        priority: r.priority,
        sourceId: r.id,
      })
    }
  }

  // --- Credit cards --------------------------------------------------------
  // Only the *current* outstanding balance is scheduled, on the next due date.
  // Ongoing card spend is already represented by the everyday burn rate, so
  // projecting a full statement every month would double-count it.
  for (const card of state.accounts) {
    if (card.kind !== 'credit' || card.archived) continue
    const owed = Math.abs(Math.min(0, card.balance))
    if (owed <= 0 || card.dueDay == null) continue

    const payer = paymentAccountFor(state, card)
    if (!payer) continue

    const due = nextDayOfMonth(card.dueDay, from)
    if (due <= to) {
      events.push({
        id: `card:${card.id}:${due}`,
        date: due,
        label: `${card.name} payment`,
        kind: 'card_payment',
        amount: owed,
        toAccountId: card.id, // clearing debt credits the card back toward zero
        fromAccountId: payer.id,
        confidence: 1,
        priority: 'critical',
        sourceId: card.id,
      })
    }
  }

  // --- Everyday spending ---------------------------------------------------
  // Drawn weekly rather than daily so the chart stays readable without lying
  // about the total.
  const daily = everydayDailyBurn(state)
  const acct = everydayAccount(state)
  if (acct && daily > 0) {
    let cursor = from
    while (cursor <= to) {
      events.push({
        id: `everyday:${cursor}`,
        date: cursor,
        label: 'Everyday spending',
        kind: 'everyday',
        amount: daily * 7,
        toAccountId: null,
        fromAccountId: acct.id,
        confidence: 0.8,
        sourceId: 'everyday',
      })
      cursor = addDays(cursor, 7)
    }
  }

  return events.sort((a, b) => (a.date < b.date ? -1 : a.date > b.date ? 1 : 0))
}

/** Everything due in the next `days`, soonest first. */
export function upcoming(state: FinancialState, days = 30): LedgerEvent[] {
  const from = today()
  return generateScheduledEvents(state, from, addDays(from, days)).filter(
    (e) => e.kind !== 'everyday',
  )
}
